name:                chain-hash-hs
version:             0.1.0.0
github:              "jbristow/chain-hash-hs"
license:             BSD3
author:              "Jon Bristow"
maintainer:          "jonthegm@yahoo.com"
copyright:           "2018 Jon Bristow"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A simple implementation of a chained hash algorithm.
category:            Cryptography

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jbristow/chain-hash-hs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cryptohash-sha256
- cmdargs

library:
  source-dirs: src

executables:
  chain-hash-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chain-hash-hs

tests:
  chain-hash-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chain-hash-hs
